Considering a new documentation approach -- permitting page generation idea

diff --git a/b/csv b/b/csv
--- a/b/csv
+++ b/b/csv
@@ -1,181 +1,104 @@
 #!/usr/bin/env bash
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"
 
-doc="$(cat <<'EOF'
-
-# csv
-
-Interface with CSV files
-
-`limit`		| Print the first n lines of a csv file
-`dedupe`	| Deduplicate a csv file
-`filter`	| Filter a csv file based on a given column and match string
-`math`		| Perform math operations on a csv file
-
-> b/csv limit -f file.csv -o output.csv			| Print the first n lines of a csv file
-> b/csv dedupe -f file.csv -o output.csv		| Deduplicate a csv file
-> b/csv filter -f file.csv -c column -m match	| Filter a csv file based on a given column and match string
-> b/csv math -f file.csv -c column -o operation	| Perform math operations on a csv file
-
-EOF
-)" && inspect "$doc" "$1"
-# =============================================================================
-
-
 
 command="$1" && shift
 
 case $command in
 
 
-
 	# =============================================================================
-	math ) doc=$(cat <<'EOF'
-# csv math
+	math )
 
-Perform math operations on a csv file
+		while getopts "f:c:o:" opt; do
+			case $opt in
+				f ) file=$OPTARG ;; #file to perform operations on
+				c ) columns=$OPTARG ;; #columns given as comma separated list
+				o ) operation=$OPTARG ;; #operation to perform
+				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
+			esac
+		done
 
-`-f`	| * The file to perform operations on
-`-c`	| * The column(s) to perform math on
-`-o`	| * The operation to perform
+		[[ -z $file ]] && echo "No file specified to perform operations on" && exit 1
+		[[ -z $columns ]] && echo "No columns specified to perform math on" && exit 1
 
-> b/csv math -f file.csv -c invoice_amount -o sum		| Sum the values in the invoice_amount column
+		declare -a valid_operations=( sum mean median mode min max range variance std_dev unique count )
 
-EOF
-	) && inspect "$doc" "$1"
-	# ======================
+		# Check if operation is valid
+		valid=false
+		for valid_operation in "${valid_operations[@]}"; do
+			if [[ $valid_operation == "$operation" ]]; then
+			valid=true
+			break
+			fi
+		done
 
-	while getopts "f:c:o:" opt; do
-		case $opt in
-			f ) file=$OPTARG ;; #file to perform operations on
-			c ) columns=$OPTARG ;; #columns given as comma separated list
-			o ) operation=$OPTARG ;; #operation to perform
-			\? ) echo "Invalid option: -$OPTARG" >&2 ;;
-		esac
-	done
-
-	[[ -z $file ]] && echo "No file specified to perform operations on" && exit 1
-	[[ -z $columns ]] && echo "No columns specified to perform math on" && exit 1
-
-	declare -a valid_operations=( sum mean median mode min max range variance std_dev unique count )
-
-	# Check if operation is valid
-	valid=false
-	for valid_operation in "${valid_operations[@]}"; do
-		if [[ $valid_operation == "$operation" ]]; then
-		valid=true
-		break
+		if [[ $valid == true ]]; then
+			csvstat -c "$columns" --"$operation" "$file"
+		else
+			b/error invalid_operation "Invalid operation: $operation"
 		fi
-	done
 
-	if [[ $valid == true ]]; then
-		csvstat -c "$columns" --"$operation" "$file"
-	else
-		b/error invalid_operation "Invalid operation: $operation"
-	fi
-
-	;;
+		;;
 
 
 
 	# =============================================================================
-	limit ) doc=$(cat <<'EOF'
-# csv limit
+	limit )
 
-Print the first n lines of a csv file
+		while getopts "f:o:" opt; do
+			case $opt in
+				f ) file=$OPTARG ;; #file to perform operations on
+				o ) output_file=$OPTARG ;; #output file
+				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
+			esac
+		done
 
-`:limit` 	| The number of rows to output
-`-f`		| * The file to perform operations on
-`-o`		| = The output file
+		limit="${1:-10}"
 
-> b/csv limit 10 -f file.csv -o output.csv		| Print the first n lines of a csv file
+		[[ -z $file ]] && echo "No file specified to perform operations on" && exit 1
 
-EOF
-	) && inspect "$doc" "$1"
-	# ======================
+		if [[ -n $output_file ]]; then
+			csvlook -n "$file" > "$output_file"
+		else
+			csvlook -n "$file"
+		fi
 
-	while getopts "f:o:" opt; do
-		case $opt in
-			f ) file=$OPTARG ;; #file to perform operations on
-			o ) output_file=$OPTARG ;; #output file
-			\? ) echo "Invalid option: -$OPTARG" >&2 ;;
-		esac
-	done
-
-	limit="${1:-10}"
-
-	[[ -z $file ]] && echo "No file specified to perform operations on" && exit 1
-
-	if [[ -n $output_file ]]; then
-		csvlook -n "$file" > "$output_file"
-	else
-		csvlook -n "$file"
-	fi
-
-	;;
+		;;
 
 
 
 	# =============================================================================
-	dedupe ) doc=$(cat <<'EOF'
+	dedupe )
 
-# csv dedupe
+		while getopts "f:o:d:" opt; do
+			case $opt in
+				f ) file=$OPTARG ;; #file to perform operations on
+				o ) output=$OPTARG ;; #output deduped
+				d ) columns=$OPTARG ;; #columns given as comma separated list
+				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
+			esac
+		done
 
-Deduplicate a csv file
-
-`-f`	| * The file to perform operations on
-`-o`	| = The output file
-`-d`	| = The columns to deduplicate on
-
-> b/csv dedupe -f file.csv -o output.csv		| Deduplicate a csv file
-
-EOF
-	) && inspect "$doc" "$1"
-	# ======================
-
-	while getopts "f:o:d:" opt; do
-		case $opt in
-			f ) file=$OPTARG ;; #file to perform operations on
-			o ) output=$OPTARG ;; #output deduped
-			d ) columns=$OPTARG ;; #columns given as comma separated list
-			\? ) echo "Invalid option: -$OPTARG" >&2 ;;
-		esac
-	done
-
-	;;
+		;;
 
 
 
 	# =============================================================================
-	filter ) doc=$(cat <<'EOF'
-# csv filter
+	filter )
 
-Filter a csv file based on a given column and match string
+		while getopts "f:c:m:b:C" opt; do
+			case $opt in
+				f ) file=$OPTARG ;; #file to perform operations on
+				c ) columns=$OPTARG ;; #columns given as comma separated list
+				m ) match=$OPTARG ;; #match string
+				b ) begins_with=$OPTARG ;; #match string
+				C ) case_insensitive=true ;; #case insensitive match
+				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
+			esac
+		done
 
-`-f`	| * The file to perform operations on
-`-c`	| * The column(s) to filter on
-`-m`	| = The match string
-`-b`	| = Match strings that begin with the given string
-`-C`	|   Perform a case insensitive match
-
-> b/csv filter -f file.csv -c column -m match	| Filter a csv file based on a given column and match string
-
-EOF
-	) && inspect "$doc" "$1"
-	# ======================
-
-	while getopts "f:c:m:b:C" opt; do
-		case $opt in
-			f ) file=$OPTARG ;; #file to perform operations on
-			c ) columns=$OPTARG ;; #columns given as comma separated list
-			m ) match=$OPTARG ;; #match string
-			b ) begins_with=$OPTARG ;; #match string
-			C ) case_insensitive=true ;; #case insensitive match
-			\? ) echo "Invalid option: -$OPTARG" >&2 ;;
-		esac
-	done
-
-	;;
+		;;
 
 
 
diff --git a/b/daily b/b/daily
--- a/b/daily
+++ b/b/daily
@@ -1,22 +1,6 @@
 #!/usr/bin/env bash
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"
 
-doc="$(cat <<'EOF'
-
-# daily
-
-Daily.co API
-
-`rooms.create`		| Create a new room
-`transcriptions.list`	| List transcriptions
-
-> b/daily rooms.create -n "My Room" -p private -l 5		| Create a new room
-
-EOF
-)" && inspect "$doc" "$1"
-# =============================================================================
-
-
 
 [ -z "$BARE_DAILY_API_KEY" ] && b/error missing_key "Daily.co API key not set (BARE_DAILY_API_KEY)" && exit 1
 
@@ -25,128 +9,95 @@ shift
 
 case $command in
 
-    rooms.create ) doc="$(cat <<'EOF'
+    rooms.create )
 
-# daily rooms.create
+		while getopts "hn:p:w:x:l:s:k:e:r:t" opt; do
+			case $opt in
+				h ) b/usage -t options -w 4 $0 \
+					-n "sets the name of the room" \
+					-p "sets the privacy of the room" \
+					-w "sets the not before date" \
+					-x "sets the expiration date" \
+					-l "sets the participants limit" \
+					-s "sets the screensharing" \
+					-k "sets the knocking" \
+					-e "sets the eject at expiration" \
+					-r "allow recording" \
+					-t "allows transcription" && exit 0 ;;
+				n ) name=${OPTARG:-$(b/random string)} ;;
+				p ) privacy=${OPTARG:-'private'} ;;
+				w ) not_before=$OPTARG ;;
+				x ) expires=$OPTARG ;;
+				l ) participants_limit=${OPTARG:-2} ;;
+				s ) screensharing=${OPTARG:-true} ;;
+				k ) knocking=${OPTARG:-true} ;;
+				e ) eject_at_expiration=${OPTARG:-false} ;;
+				r ) recordable=${OPTARG:-'cloud'} ;;
+				t ) transcribable=${OPTARG:-false} ;;
+				\? ) echo "Invalid option: -$OPTARG" ;;
+			esac
+		done
 
-Create a new room
+		# Ensure the variables are set to a valid JSON value
+		[ -z "$screensharing" ] && screensharing=true
+		[ -z "$knocking" ] && knocking=true
+		[ -z "$eject_at_expiration" ] && eject_at_expiration=false
+		[ -z "$transcribable" ] && transcribable=false
+		[ -z "$participants_limit" ] && participants_limit=2
 
-`-n`	| * Name of the room
-`-p`	| Privacy of the room (public or private)
-`-w`	| Not before date
-`-x`	| Expiration date
-`-l`	| Participants limit
-`-s`	| Screensharing
-`-k`	| Knocking
-`-e`	| Eject at expiration
-`-r`	| Allow recording
-`-t`	| Allow transcription
+		# Start of the JSON payload
+		json_payload=$(jq -n \
+			--arg name "$name" \
+			--arg privacy "$privacy" \
+			--argjson screensharing "$screensharing" \
+			--argjson knocking "$knocking" \
+			--argjson eject_at_expiration "$eject_at_expiration" \
+			--arg transcribable "$transcribable" \
+			--argjson participants_limit "$participants_limit" \
+			--arg not_before "$not_before" \
+			'{
+				"name": $name,
+				"privacy": $privacy,
+				"properties": {
+					"enable_screenshare": $screensharing,
+					"enable_knocking": $knocking,
+					"enable_advanced_chat": true,
+					"eject_at_room_exp": $eject_at_expiration,
+					"enable_transcription_storage": true,
+					"max_participants": $participants_limit,
+					"nbf": $not_before
+				}
+			}')
 
-> b/daily rooms.create -n "My Room" -p private -l 5		| Create a new room
+		# Conditionally add 'enable_recording' to the JSON payload
+		if [ -n "$recordable" ]; then
+			json_payload=$(echo $json_payload | jq --arg recordable "$recordable" '.properties.enable_recording = $recordable')
+		fi
 
-EOF
-	)" && inspect "$doc" "$1"
-	# ======================
+		# Conditionally add 'exp' to the JSON payload
+		if [ -n "$expires" ]; then
+			json_payload=$(echo $json_payload | jq --arg expires "$expires" '.properties.exp = $expires')
+		fi
 
-	while getopts "hn:p:w:x:l:s:k:e:r:t" opt; do
-		case $opt in
-			h ) b/usage -t options -w 4 $0 \
-				-n "sets the name of the room" \
-				-p "sets the privacy of the room" \
-				-w "sets the not before date" \
-				-x "sets the expiration date" \
-				-l "sets the participants limit" \
-				-s "sets the screensharing" \
-				-k "sets the knocking" \
-				-e "sets the eject at expiration" \
-				-r "allow recording" \
-				-t "allows transcription" && exit 0 ;;
-			n ) name=${OPTARG:-$(b/random string)} ;;
-			p ) privacy=${OPTARG:-'private'} ;;
-			w ) not_before=$OPTARG ;;
-			x ) expires=$OPTARG ;;
-			l ) participants_limit=${OPTARG:-2} ;;
-			s ) screensharing=${OPTARG:-true} ;;
-			k ) knocking=${OPTARG:-true} ;;
-			e ) eject_at_expiration=${OPTARG:-false} ;;
-			r ) recordable=${OPTARG:-'cloud'} ;;
-			t ) transcribable=${OPTARG:-false} ;;
-			\? ) echo "Invalid option: -$OPTARG" ;;
-		esac
-	done
+		response=$(curl https://api.daily.co/v1/rooms -s \
+			-H "Content-Type: application/json" \
+			-H "Authorization: Bearer $BARE_DAILY_API_KEY" \
+			-d "$json_payload") || { b/error api_error "Failed to create room"; exit 1; }
 
-	# Ensure the variables are set to a valid JSON value
-	[ -z "$screensharing" ] && screensharing=true
-	[ -z "$knocking" ] && knocking=true
-	[ -z "$eject_at_expiration" ] && eject_at_expiration=false
-	[ -z "$transcribable" ] && transcribable=false
-	[ -z "$participants_limit" ] && participants_limit=2
+		echo "$response" | jq
 
-	# Start of the JSON payload
-	json_payload=$(jq -n \
-		--arg name "$name" \
-		--arg privacy "$privacy" \
-		--argjson screensharing "$screensharing" \
-		--argjson knocking "$knocking" \
-		--argjson eject_at_expiration "$eject_at_expiration" \
-		--arg transcribable "$transcribable" \
-		--argjson participants_limit "$participants_limit" \
-		--arg not_before "$not_before" \
-		'{
-			"name": $name,
-			"privacy": $privacy,
-			"properties": {
-				"enable_screenshare": $screensharing,
-				"enable_knocking": $knocking,
-				"enable_advanced_chat": true,
-				"eject_at_room_exp": $eject_at_expiration,
-				"enable_transcription_storage": true,
-				"max_participants": $participants_limit,
-				"nbf": $not_before
-			}
-		}')
-
-	# Conditionally add 'enable_recording' to the JSON payload
-	if [ -n "$recordable" ]; then
-		json_payload=$(echo $json_payload | jq --arg recordable "$recordable" '.properties.enable_recording = $recordable')
-	fi
-
-	# Conditionally add 'exp' to the JSON payload
-	if [ -n "$expires" ]; then
-		json_payload=$(echo $json_payload | jq --arg expires "$expires" '.properties.exp = $expires')
-	fi
-
-	response=$(curl https://api.daily.co/v1/rooms -s \
-		-H "Content-Type: application/json" \
-		-H "Authorization: Bearer $BARE_DAILY_API_KEY" \
-		-d "$json_payload") || { b/error api_error "Failed to create room"; exit 1; }
-
-	echo "$response" | jq
-
-	;;
+		;;
 
 
-	transcriptions.list ) doc="$(cat <<'EOF'
+	transcriptions.list )
 
-# daily transcriptions.list
+		response=$(curl https://api.daily.co/v1/transcript -s \
+			-H "Content-Type: application/json" \
+			-H "Authorization: Bearer $BARE_DAILY_API_KEY") || { b/error api_error "Failed to list transcriptions"; exit 1; }
 
-List transcriptions
+		echo "$response" | jq
 
-`n/a`	| No options
-
-> daily transcriptions.list		| List transcriptions
-
-EOF
-	)" && inspect "$doc" "$1"
-	# ======================
-
-	response=$(curl https://api.daily.co/v1/transcript -s \
-		-H "Content-Type: application/json" \
-		-H "Authorization: Bearer $BARE_DAILY_API_KEY") || { b/error api_error "Failed to list transcriptions"; exit 1; }
-
-	echo "$response" | jq
-
-	;;
+		;;
 
 
 esac
diff --git a/b/export b/b/export
--- a/b/export
+++ b/b/export
@@ -1,87 +1,62 @@
 #!/usr/bin/env bash
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"
 
-doc="$(cat <<'EOF'
-
-# export
-
-Export data to various locations/formats
-
-`digital-ocean`	| Export (upload) data to a Digital Ocean space
-
-> b/export digital-ocean -f file.csv -b bucket -k key -s secret | Export (upload) data to a Digital Ocean space
-
-EOF
-)" && inspect "$doc" "$1"
 
 command="$1" && shift
 
 case $command in
 
 	# =============================================================================
-	digital-ocean ) doc=$(cat <<'EOF'
-# export digital-ocean
+	digital-ocean )
 
-Export (upload) data to a Digital Ocean space
+		[[ -z $BARE_DO_SPACES_ACCESS_KEY ]] && echo "No Digital Ocean Spaces key found" && exit 1
+		[[ -z $BARE_DO_SPACES_SECRET ]] && echo "No Digital Ocean Spaces secret found" && exit 1
 
-`-f`	| * The file to export
-`-p`	| * The DO path to write to
-`-k`	|   The key to use
-`-s`	|   The secret to use
+		key=$BARE_DO_SPACES_ACCESS_KEY
+		secret=$BARE_DO_SPACES_SECRET
+		public=false
+		while getopts "f:p:Pk:s:" opt; do
+			case $opt in
+				f ) file=$OPTARG ;; # file to export
+				p ) path=$OPTARG ;; # DO path to export to
+				P ) public=true ;;
+				k ) key=$OPTARG ;;
+				s ) secret=$OPTARG ;;
+				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
+			esac
+		done
 
-> b/export digital-ocean -f file.csv -b bucket -k key -s secret
+		[[ -z $file ]] && echo "No file specified to export" && exit 1
+		[[ -z $path ]] && echo "No DO path specified to export to" && exit 1
+		[[ -z $key ]] && echo "No key specified to use" && exit 1
+		[[ -z $secret ]] && echo "No secret specified to use" && exit 1
 
-EOF
-) && inspect "$doc" "$1"
-	# ======================
+		# get the mime type of the file
+		content_type=$(file --mime-type -b "$file")
 
-	[[ -z $BARE_DO_SPACES_ACCESS_KEY ]] && echo "No Digital Ocean Spaces key found" && exit 1
-	[[ -z $BARE_DO_SPACES_SECRET ]] && echo "No Digital Ocean Spaces secret found" && exit 1
+		STORAGETYPE="STANDARD"
 
-	key=$BARE_DO_SPACES_ACCESS_KEY
-	secret=$BARE_DO_SPACES_SECRET
-	public=false
-	while getopts "f:p:Pk:s:" opt; do
-		case $opt in
-			f ) file=$OPTARG ;; # file to export
-			p ) path=$OPTARG ;; # DO path to export to
-			P ) public=true ;;
-			k ) key=$OPTARG ;;
-			s ) secret=$OPTARG ;;
-			\? ) echo "Invalid option: -$OPTARG" >&2 ;;
-		esac
-	done
+		space_path="/$path"
+		space="${BARE_DO_SPACE}"
+		date=$(date +"%a, %d %b %Y %T %z")
+		[ "$public" == true ] && acl="x-amz-acl:public-read" || acl="x-amz-acl:private"
+		storage_type="x-amz-storage-class:${STORAGETYPE}"
+		string="PUT\n\n$content_type\n$date\n$acl\n$storage_type\n/$space$space_path"
+		signature=$(echo -en "${string}" | openssl sha1 -hmac "${BARE_DO_SPACES_SECRET}" -binary | base64)
+		response=$(curl -s -X PUT -T "$BARE_HOME/.nb/$file" \
+		-H "Host: $space.${BARE_DO_REGION}.digitaloceanspaces.com" \
+		-H "Date: $date" \
+		-H "Content-Type: $content_type" \
+		-H "$storage_type" \
+		-H "$acl" \
+		-H "Authorization: AWS ${BARE_DO_SPACES_ACCESS_KEY}:$signature" \
+		"https://$space.${BARE_DO_REGION}.digitaloceanspaces.com$space_path")
 
-	[[ -z $file ]] && echo "No file specified to export" && exit 1
-	[[ -z $path ]] && echo "No DO path specified to export to" && exit 1
-	[[ -z $key ]] && echo "No key specified to use" && exit 1
-	[[ -z $secret ]] && echo "No secret specified to use" && exit 1
+		# echo the digital ocean url of the file
+		echo "https://$space.${BARE_DO_REGION}.digitaloceanspaces.com$space_path"
 
-	# get the mime type of the file
-	content_type=$(file --mime-type -b "$file")
-
-	STORAGETYPE="STANDARD"
-
-	space_path="/$path"
-	space="${BARE_DO_SPACE}"
-	date=$(date +"%a, %d %b %Y %T %z")
-	[ "$public" == true ] && acl="x-amz-acl:public-read" || acl="x-amz-acl:private"
-	storage_type="x-amz-storage-class:${STORAGETYPE}"
-	string="PUT\n\n$content_type\n$date\n$acl\n$storage_type\n/$space$space_path"
-	signature=$(echo -en "${string}" | openssl sha1 -hmac "${BARE_DO_SPACES_SECRET}" -binary | base64)
-	response=$(curl -s -X PUT -T "$BARE_HOME/.nb/$file" \
-	-H "Host: $space.${BARE_DO_REGION}.digitaloceanspaces.com" \
-	-H "Date: $date" \
-	-H "Content-Type: $content_type" \
-	-H "$storage_type" \
-	-H "$acl" \
-	-H "Authorization: AWS ${BARE_DO_SPACES_ACCESS_KEY}:$signature" \
-	"https://$space.${BARE_DO_REGION}.digitaloceanspaces.com$space_path")
-
-	# echo the digital ocean url of the file
-	echo "https://$space.${BARE_DO_REGION}.digitaloceanspaces.com$space_path"
-
-	;;
+		;;
 
 	* ) echo "Invalid command: $command" && exit 1 ;;
+	
 esac
