big changes -- improves documentation approach, adds bare interpreter

diff --git a/b/csv b/b/csv
--- a/b/csv
+++ b/b/csv
@@ -2,32 +2,51 @@
 # Interface with CSV files
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"
 
-[[ -z "$1" ]] && b/usage -w 8 -t "commands" $0 \
-	"<csv_file>"	"* The csv file to operate on" \
-	limit			"  Print the first n lines of a csv file" \
-	dedupe			"  Deduplicate a csv file" \
-	filter			"  Filter a csv file based on a given column and match string" \
-	math			"  Perform math operations on a csv file"
+# ================================== DOC ===================================
 
-file="$1"
-command="$2"
-shift 2 # Shift off the first two arguments
+declare doc_name="csv"
+declare doc_description="Interface with CSV files"
+
+declare -a doc_options=(
+	"limit"		"Print the first n lines of a csv file"
+	"dedupe"	"Deduplicate a csv file"
+	"filter"	"Filter a csv file based on a given column and match string"
+	"math"		"Perform math operations on a csv file"
+) && [[ "$1" == '--inspect' ]] && return 0
+
+# ==========================================================================
+
+
+
+command="$1" && shift
 
 case $command in
 
-	math ) 
-		# getopts for -c (columns to perform math on)
-		while getopts "c:o:" opt; do
+	math )
+
+		# ============== DOC ==============
+		doc_name+=" math"
+		doc_description="Perform math operations on a csv file"
+		declare -a doc_options=(
+			"-f"		"* The file to perform operations on"
+			"-c"		"* The column(s) to perform math on"
+			"-o"		"* The operation to perform"
+		) && [[ "$1" == '--inspect' ]] && return 0
+		# ================================
+
+		while getopts "f:c:o:" opt; do
 			case $opt in
+				f ) file=$OPTARG ;; #file to perform operations on
 				c ) columns=$OPTARG ;; #columns given as comma separated list
 				o ) operation=$OPTARG ;; #operation to perform
 				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
 			esac
 		done
 
+		[[ -z $file ]] && echo "No file specified to perform operations on" && exit 1
 		[[ -z $columns ]] && echo "No columns specified to perform math on" && exit 1
 
-		valid_operations=(
+		declare -a valid_operations=(
 			"sum"		"mean"		"median"
 			"mode"		"min"		"max"
 			"range"		"variance"	"std_dev"
@@ -35,22 +54,35 @@ case $command in
 		)
 
 		# Check if operation is valid
-		if [[ " ${valid_operations[@]} " =~ " ${operation} " ]]; then
-			csvstat -c "$columns" --$operation $file
+		valid=false
+		for valid_operation in "${valid_operations[@]}"; do
+			if [[ $valid_operation == $operation ]]; then
+				valid=true
+				break
+			fi
+		done
+
+		if [[ $valid == true ]]; then
+			csvstat -c "$columns" --"$operation" "$file"
 		else b/error invalid_operation "Invalid operation: $operation"; fi
 		;;
 
 	limit )
 
-		[[ -z $1 ]] && b/usage -w 8 -t "options" $0 \
-			"<limit>"	"* The number of rows to print" \
-			"-o"		"  The output file to write to" \
-			"-P"		"  Print the output in a pretty table format"
+		# ============== DOC ==============
+		doc_name+=" limit"
+		doc_description="Print the first n lines of a csv file"
+		declare -a doc_options=(
+			"-f"		"* The file to perform operations on"
+			"-o"		"= The output file"
+			"-P"		"  Print the output"
+			"-J"		"  Return the output as JSON"
+		) && [[ "$1" == '--inspect' ]] && return 0
+		# ================================
 
-		limit="$1" && shift
-		print=false
-		while getopts ":o:PJ" opt; do
+		while getopts "f:o:PJ" opt; do
 			case $opt in
+				f ) file=$OPTARG ;; #file to perform operations on
 				o ) output_file=$OPTARG ;; #output file
 				P ) print=true ;;
 				J ) return_json=true ;;
@@ -58,56 +90,53 @@ case $command in
 			esac
 		done
 
-		if [[ -n $return_json ]]; then
-			output=$(head -n $(($limit + 1)) $file | csvjson)
-		elif [[ $print = true ]]; then
-			output=$(head -n $(($limit + 1)) $file | csvlook)
-		else
-			output=$(head -n $(($limit + 1)) $file)
-		fi
+		[[ -z $file ]] && echo "No file specified to perform operations on" && exit 1
 
-		if [[ -z $output_file ]]; then
-			echo "$output"
-		else
-			echo "$output" > "$output_file"
-		fi
+		# Check if the file exists
+		[[ ! -f $file ]] && b/error file_not_found "File not found: $file" && exit 1
+
 		;;
 
 	dedupe )
-		# getopts for -d (dynamic deduplication)
-		while getopts "f:d:" opt; do
+
+		# ============== DOC ==============
+		doc_name+=" dedupe"
+		doc_description="Deduplicate a csv file"
+		declare -a doc_options=(
+			"-f"		"* The file to perform operations on"
+			"-o"		"= The output file"
+			"-d"		"= The columns to deduplicate on"
+		) && [[ "$1" == '--inspect' ]] && return 0
+		# ================================
+
+		while getopts "f:o:d:" opt; do
 			case $opt in
+				f ) file=$OPTARG ;; #file to perform operations on
 				o ) output=$OPTARG ;; #output deduped
 				d ) columns=$OPTARG ;; #columns given as comma separated list
 				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
 			esac
 		done
 
-		[[ -z $output ]] && output="./var/deduped.$(date +%s).csv"
-
-		if [[ -n $columns ]]; then
-			tmp_csv="./tmp/$(b/random string 30).csv"
-			csvsort -c "$columns" $file > $tmp_csv
-			head -1 $file > $output
-			tail -n +2 $tmp_csv | awk -v cols="$columns" -F, '!seen[$cols]++' >> $output
-			rm $tmp_csv
-		else
-			csvsort "$file" | uniq
-		fi
 		;;
 
 	filter )
 
-		[[ -z $1 ]] && b/usage -w 8 -t "options" $0 \
-			"-c"		"* The column(s) to filter on" \
-			"-m"		"= The match string" \
-			"-b"		"= Match strings that begin with the given string" \
+		# ============== DOC ==============
+		doc_name+=" filter"
+		doc_description="Filter a csv file based on a given column and match string"
+		declare -a doc_options=(
+			"-f"		"* The file to perform operations on"
+			"-c"		"* The column(s) to filter on"
+			"-m"		"= The match string"
+			"-b"		"= Match strings that begin with the given string"
 			"-C"		"  Perform a case insensitive match"
+		) && [[ "$1" == '--inspect' ]] && return 0
+		# ================================
 
-		# getopts for -c (columns to filter on)
-		case_insentivie=false
-		while getopts "c:m:C" opt; do
+		while getopts "f:c:m:b:C" opt; do
 			case $opt in
+				f ) file=$OPTARG ;; #file to perform operations on
 				c ) columns=$OPTARG ;; #columns given as comma separated list
 				m ) match=$OPTARG ;; #match string
 				b ) begins_with=$OPTARG ;; #match string
@@ -116,17 +145,6 @@ case $command in
 			esac
 		done
 
-		[[ -z $columns ]] && echo "No columns specified to filter on" && exit 1
-
-		if [[ -n $begins_with ]]; then
-			csvgrep -c "$columns" -r "^$match" $file
-		elif [[ $case_insensitive = true ]]; then
-			csvgrep -c "$columns" -r "(?i)$match" $file
-		else
-			csvgrep -c "$columns" -m "$match" $file
-		fi
 		;;
-
-	* ) echo "Invalid command" && exit 1 ;;
 
 esac
diff --git a/b/ffmpeg b/b/ffmpeg
--- a/b/ffmpeg
+++ b/b/ffmpeg
@@ -1,25 +1,18 @@
 #!/usr/bin/env bash
-# Video and audio manipulation with ffmpeg
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"
 
+# ================================== DOC ===================================
+declare doc_name="ffmpeg"
+declare doc_description="Video and audio manipulation with ffmpeg"
+declare -a doc_options=(
+	"video-to-mp3" "Convert video to mp3"
+	"video.chunk" "Takes a file as input and separates it into equal chunks"
+	"video.merge" "Merges given chunks into a single file"
+	"video.360" "Converts a video to 360p"
+	"video.720" "Converts a video to 720p"
+) && [[ "$1" == '--inspect' ]] && return 0
+
 [ ! -x $(command -v ffmpeg) ] && b/error "ffmpeg not installed" "Please install ffmpeg to use this feature"
-
-
-
-
-
-# Chunk video
-if [ -z "$1" ]; then
-    b/usage -t commands -w 12 $0 \
-        video.chunk "Takes a file as input and separates it into equal chunks" \
-        video.merge "Merges given chunks into a single file" \
-        video.360 "Converts a video to 360p" \
-        video.720 "Converts a video to 720p"
-    exit 0
-fi
-
-
-
 
 
 # Check if a file exists and is not empty
@@ -55,12 +48,15 @@ case $command in
     # Convert video to mp3
     # ========================================================================
     video-to-mp3)
-
-        [ -z "$1" ] && b/usage -t options -w 4 $0 \
-            -v "* Input file" \
-            -o "  Output file (default: ./tmp/xxxxxxxxxx)" \
-            -s "  Suppress process" \
-            -S "  Suppress output" && exit 0
+	
+		doc_name+=" video-to-mp3"
+		doc_description="Convert video to mp3"
+		declare -a doc_options=(
+			"-v"		"* Input file"
+			"-o"		"  Output file (default: ./tmp/xxxxxxxxxx)"
+			"-s"		"  Suppress process"
+			"-S"		"  Suppress output"
+		) && [[ "$1" == '--inspect' ]] && return 0
 
         output="./tmp/$(openssl rand -hex 8).mp3"
 
@@ -70,6 +66,7 @@ case $command in
                 o) output="$OPTARG" ;;
                 s) suppress_process=true ;;
                 S) suppress_output=true ;;
+				*) b/error invalid_option "Invalid option: -$OPTARG" ;;
             esac
         done
 
@@ -80,7 +77,7 @@ case $command in
             ffmpeg -i "$video" -vn -acodec libmp3lame "$output"
         fi
 
-        [ ! -n "$suppress_output" ] && echo '{"mp3_file": "'$output'"}' | jq -r && exit 0 || exit 0
+        [[ ! -n "$suppress_output" ]] && echo '{"mp3_file": "'$output'"}' | jq -r && exit 0 || exit 0
 
         ;;
 
@@ -88,11 +85,14 @@ case $command in
 
     # ========================================================================
     video.chunk)
-
-        b/usage -t options -w 4 $0 \
-            -v "* Input file" \
-            -o "  Output folder (default: ./tmp/xxxxxxxxxx)" \
-            -d "  Chunk duration in seconds (default: 60)"
+	
+		doc_name+=" video.chunk"
+		doc_description="Takes a file as input and separates it into equal chunks"
+		declare -a doc_options=(
+			"-v"		"* Input file"
+			"-o"		"  Output folder (default: ./tmp/xxxxxxxxxx)"
+			"-d"		"  Duration of each chunk in seconds (default: 60)"
+		) && [[ "$1" == '--inspect' ]] && return 0
 
         duration=60
         output="./tmp/$(openssl rand -hex 8)"
@@ -102,6 +102,7 @@ case $command in
                 v) video="$OPTARG" ;;
                 o) output="$OPTARG" ;;
                 d) duration="$OPTARG" ;;
+				*) b/error invalid_option "Invalid option: -$OPTARG" ;;
             esac
         done
         
@@ -158,6 +159,14 @@ case $command in
 
     # ========================================================================
     merge)
+
+		doc_name+=" merge"
+		doc_description="Merges given chunks into a single file"
+		declare -a doc_options=(
+			"-v"		"* Input files"
+			"-o"		"  Output file"
+		) && [[ "$1" == '--inspect' ]] && return 0
+
         [ -z "$1" ] && b/error "No input files provided" "Please provide files to merge" && exit 1
         [ -z "$2" ] && b/error "No output file provided" "Please provide a file to merge" && exit 1
         ffmpeg -i "concat:$1" -c copy "$2"
@@ -168,11 +177,14 @@ case $command in
     # ========================================================================
     video.240)
 
-        [ -z "$1" ] && b/usage -t options -w 4 $0 \
-            -v "* Input file" \
-            -o "  Output file (default: ./tmp/xxxxxxxxxx)" \
-            -s "  Suppress process" \
-            -S "  Suppress output" && exit 0
+		doc_name+=" video.240"
+		doc_description="Converts a video to 240p"
+		declare -a doc_options=(
+			"-v"		"* Input file"
+			"-o"		"  Output file (default: ./tmp/xxxxxxxxxx)"
+			"-s"		"  Suppress process"
+			"-S"		"  Suppress output"
+		) && [[ "$1" == '--inspect' ]] && return 0
 
         output="./tmp/$(openssl rand -hex 8).mp4"
 
@@ -182,6 +194,7 @@ case $command in
                 o) output="$OPTARG" ;;
                 s) suppress_process=true ;;
                 S) suppress_output=true ;;
+				*) b/error invalid_option "Invalid option: -$OPTARG" ;;
             esac
         done
 
@@ -195,12 +208,15 @@ case $command in
 
     # ========================================================================
     video.360)
-
-        [ -z "$1" ] && b/usage -t options -w 4 $0 \
-            -v "* Input file" \
-            -o "  Output file (default: ./tmp/xxxxxxxxxx)" \
-            -s "  Suppress process" \
-            -S "  Suppress output" && exit 0
+	
+		doc_name+=" video.360"
+		doc_description="Converts a video to 360p"
+		declare -a doc_options=(
+			"-v"		"* Input file"
+			"-o"		"  Output file (default: ./tmp/xxxxxxxxxx)"
+			"-s"		"  Suppress process"
+			"-S"		"  Suppress output"
+		) && [[ "$1" == '--inspect' ]] && return 0
 
         output="./tmp/$(openssl rand -hex 8).mp4"
 
@@ -210,6 +226,7 @@ case $command in
                 o) output="$OPTARG" ;;
                 s) suppress_process=true ;;
                 S) suppress_output=true ;;
+				*) b/error invalid_option "Invalid option: -$OPTARG" ;;
             esac
         done
 
@@ -225,11 +242,14 @@ case $command in
     # ========================================================================
     video.720)
 
-        [ -z "$1" ] && b/usage -t options -w 4 $0 \
-            -v "* Input file" \
-            -o "  Output file (default: ./tmp/xxxxxxxxxx)" \
-            -s "  Suppress process" \
-            -S "  Suppress output" && exit 0
+		doc_name+=" video.720"
+		doc_description="Converts a video to 720p"
+		declare -a doc_options=(
+			"-v"		"* Input file"
+			"-o"		"  Output file (default: ./tmp/xxxxxxxxxx)"
+			"-s"		"  Suppress process"
+			"-S"		"  Suppress output"
+		) && [[ "$1" == '--inspect' ]] && return 0
 
         output="./tmp/$(openssl rand -hex 8).mp4"
 
@@ -239,6 +259,7 @@ case $command in
                 o) output="$OPTARG" ;;
                 s) suppress_process=true ;;
                 S) suppress_output=true ;;
+				*) b/error invalid_option "Invalid option: -$OPTARG" ;;
             esac
         done
 
@@ -247,13 +268,6 @@ case $command in
 
         [ ! -n "$suppress_output" ] && echo '{"720p_file": "'$output'"}' && exit 0 || exit 0
 
-        ;;
-
-
-
-    # ========================================================================
-    *)
-        b/error "Invalid command" "Please provide a valid command" && exit 1
         ;;
 
 
diff --git a/b/postmark b/b/postmark
--- a/b/postmark
+++ b/b/postmark
@@ -1,23 +1,20 @@
 #!/usr/bin/env bash
-# Postmark API client
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"
+
+# ================================== DOC ===================================
+declare doc_name="postmark"
+declare doc_description="Send and receive email with Postmark"
+declare -a doc_options=(
+	"send"		"Send email"
+) && [[ "$1" == '--inspect' ]] && return 0
+# ==========================================================================
 
 [ ! -x "$(command -v curl)" ] && echo "🚨 curl is not installed" && exit 1
 [ ! -x "$(command -v jq)" ] && echo "🚨 jq is not installed" && exit 1
 [ -z "$POSTMARK_SERVER_TOKEN" ] && echo "🚨 POSTMARK_SERVER_TOKEN environment variable is not set" && exit 1
 
-[[ -z "$1" ]] && b/usage -w 4 $0 \
-    "-t" "Recipient email address" \
-    "-s" "Email subject" \
-    "-b" "HTML body" \
-    "-f" "From email address" \
-    "-r" "Reply-to email address" \
-    "-x" "Text body" \
-    "-j" "JSON string" \
-    "-i" "JSON file" && exit 0
 
-command="$1"
-shift
+command="$1" && shift
 
 curlPostmarkRequest() {
     url="$1"
@@ -41,38 +38,31 @@ case $command in
     # ========================================================
     send )
 
-        [[ -z "$1" ]] && b/usage -w 4 "$0 send" \
-            -t "* Recipient email address" \
-            -s "* Email subject" \
-            -b "* HTML body" \
-            -f "* From email address" \
-            -r "  Reply-to email address" \
-            -x "~ Text body" \
-            -j "  JSON string" \
-            -i "  JSON file" && exit 0
+		doc_name+=" send"
+		doc_description="Send email"
+		declare -a doc_options=(
+			"to"		"* Recipient email address"
+			"subject"	"* Email subject"
+			"htmlBody"	"* HTML body"
+			"from"		"* From email address"
+			"replyTo"	"  Reply-to email address"
+			"textBody"	"= Text body"
+			"jsonString"	"  JSON string"
+			"jsonFile"	"  JSON file"
+		) && [[ "$1" == '--inspect' ]] && return 0
 
         while getopts ":t:s:b:f:r:x:j:f:" opt; do
             case $opt in
-                t )
-                    to="$OPTARG" ;;
-                s )
-                    subject="$OPTARG" ;;
-                b )
-                    htmlBody="$OPTARG" ;;
-                f )
-                    from="$OPTARG" ;;
-                r )
-                    replyTo="$OPTARG" ;;
-                x )
-                    textBody="$OPTARG" ;;
-                j )
-                    jsonString="$OPTARG" ;;
-                i )
-                    jsonFile="$OPTARG" ;;
-                \? )
-                    echo "🌿 Invalid option: -$OPTARG" && exit 1 ;;
-                : )
-                    echo "🌿 Option -$OPTARG requires an argument" && exit 1 ;;
+                t ) to="$OPTARG" ;;
+                s ) subject="$OPTARG" ;;
+                b ) htmlBody="$OPTARG" ;;
+                f ) from="$OPTARG" ;;
+                r ) replyTo="$OPTARG" ;;
+                x ) textBody="$OPTARG" ;;
+                j ) jsonString="$OPTARG" ;;
+                i ) jsonFile="$OPTARG" ;;
+                \? ) echo "🌿 Invalid option: -$OPTARG" && exit 1 ;;
+                : ) echo "🌿 Option -$OPTARG requires an argument" && exit 1 ;;
             esac
         done
         shift $((OPTIND -1))
@@ -118,8 +108,4 @@ case $command in
         curlPostmarkRequest "https://api.postmarkapp.com/email" "$payload" | jq
         ;;
 
-    # ========================================================
-    * )
-        echo "🌿 Invalid command: $command" && exit 1
-        ;;
 esac
diff --git a/bare b/bare
--- a/bare
+++ b/bare
@@ -1,27 +1,31 @@
 #!/usr/bin/env bash
-# Call a script from the b/ directory.
-
+# Call a script from the b/ directory, passing along any subsequent arguments
 source "$(dirname "${BASH_SOURCE[0]}")/lib/init"
 
-declare -A scopes
-for scope in $(ls b/*); do
-    if [[ -f $scope ]]; then
-        scope_name=$(basename $scope)
-        scope_desc=$(sed -n '2p' $scope | cut -c 3-)
-        scopes[$scope_name]=$scope_desc
-    fi
+# ================================== DOC ===================================
+declare doc_name="bare"
+declare doc_description="A collection of scripts for common tasks"
+declare -a doc_options=(
+	":command"	"The command to run"
+) && [[ "$1" == '--inspect' ]] && return 0
+# ==========================================================================
+
+# Get the list of allowed commands from the b/ directory
+mapfile -t allowed_commands < <(find b/ -type f ! -name ".*" -exec basename {} \;)
+
+command="$1" && shift
+
+found=false
+for cmd in "${allowed_commands[@]}"; do
+	if [[ $cmd == $command ]]; then
+		found=true
+		break
+	fi
 done
 
-[[ -z "$1" ]] && {
-	args=""
-	for scope in $(echo "${!scopes[@]}" | tr ' ' '\n' | sort); do
-		args+="$scope \"${scopes[$scope]}\" "
-	done
-	eval "b/usage -w 8 -t \"scope\" "bare" $args"
-	exit 0
-}
-
-# make sure the first argument is a valid scope.
-[[ -z "${scopes[$1]}" ]] && b/error invalid_scope "Only executables in the b/ directory are allowed."
-
-command="$1" && shift && "b/$command" "$@" # vroom vroom
+if $found; then
+	"b/$command" "$@" # vroom vroom
+else
+	echo "Error: Invalid command"
+	exit 1
+fi
