changes bin/ to b/ (avoid 'binary' confusion and could be thought of as short for 'bare'

diff --git a/b/daily b/b/daily
--- a/b/daily
+++ b/b/daily
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-[ -z "$DAILY_API_KEY" ] && bin/error missing_key "Daily.co API key not set (DAILY_API_KEY)" && exit 1
+[ -z "$DAILY_API_KEY" ] && b/error missing_key "Daily.co API key not set (DAILY_API_KEY)" && exit 1
 
 command=$1
 shift
@@ -12,7 +12,7 @@ case $command in
 
         while getopts "hn:p:w:x:l:s:k:e:r:t" opt; do
             case $opt in
-                h ) bin/usage -t options -w 4 $0 \
+                h ) b/usage -t options -w 4 $0 \
                     -n "sets the name of the room" \
                     -p "sets the privacy of the room" \
                     -w "sets the not before date" \
@@ -23,7 +23,7 @@ case $command in
                     -e "sets the eject at expiration" \
                     -r "allow recording" \
                     -t "allows transcription" && exit 0 ;;
-                n ) name=${OPTARG:-$(bin/random string)} ;;
+                n ) name=${OPTARG:-$(b/random string)} ;;
                 p ) privacy=${OPTARG:-'private'} ;;
                 w ) not_before=$OPTARG ;;
                 x ) expires=$OPTARG ;;
@@ -81,7 +81,7 @@ case $command in
         response=$(curl https://api.daily.co/v1/rooms -s \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer $DAILY_API_KEY" \
-            -d "$json_payload") || { bin/error api_error "Failed to create room"; exit 1; }
+            -d "$json_payload") || { b/error api_error "Failed to create room"; exit 1; }
 
         echo $response | jq
 
@@ -94,7 +94,7 @@ case $command in
 
         response=$(curl https://api.daily.co/v1/transcript -s \
             -H "Content-Type: application/json" \
-            -H "Authorization: Bearer $DAILY_API_KEY") || { bin/error api_error "Failed to list transcriptions"; exit 1; }
+            -H "Authorization: Bearer $DAILY_API_KEY") || { b/error api_error "Failed to list transcriptions"; exit 1; }
 
         echo $response | jq
 
@@ -102,7 +102,7 @@ case $command in
         
 
     * )
-        bin/error invalid_command "Invalid command: $command"
+        b/error invalid_command "Invalid command: $command"
         exit 1
         ;;
 
diff --git a/b/ffmpeg b/b/ffmpeg
--- a/b/ffmpeg
+++ b/b/ffmpeg
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-[ ! -x $(command -v ffmpeg) ] && bin/error "ffmpeg not installed" "Please install ffmpeg to use this feature" && exit 1
+[ ! -x $(command -v ffmpeg) ] && b/error "ffmpeg not installed" "Please install ffmpeg to use this feature" && exit 1
 
 
 
@@ -8,7 +8,7 @@
 
 # Chunk video
 if [ -z "$1" ]; then
-    bin/usage -t commands -w 12 $0 \
+    b/usage -t commands -w 12 $0 \
         video.chunk "Takes a file as input and separates it into equal chunks" \
         video.merge "Merges given chunks into a single file" \
         video.360 "Converts a video to 360p" \
@@ -22,8 +22,8 @@ fi
 
 # Check if a file exists and is not empty
 check_file() {
-    [ -z "$1" ] && bin/error "No input file provided" "Please provide a file to convert" && exit 1
-    [ ! -f "$1" ] && bin/error "File not found" "Please provide a valid file" && exit 1
+    [ -z "$1" ] && b/error "No input file provided" "Please provide a file to convert" && exit 1
+    [ ! -f "$1" ] && b/error "File not found" "Please provide a valid file" && exit 1
 }
 
 # Run ffmpeg command
@@ -53,7 +53,7 @@ case $command in
     # ========================================================================
     video-to-mp3)
 
-        [ -z "$1" ] && bin/usage -t options -w 4 $0 \
+        [ -z "$1" ] && b/usage -t options -w 4 $0 \
             -v "* Input file" \
             -o "  Output file (default: ./tmp/xxxxxxxxxx)" \
             -s "  Suppress process" \
@@ -86,7 +86,7 @@ case $command in
     # ========================================================================
     video.chunk)
 
-        bin/usage -t options -w 4 $0 \
+        b/usage -t options -w 4 $0 \
             -v "* Input file" \
             -o "  Output folder (default: ./tmp/xxxxxxxxxx)" \
             -d "  Chunk duration in seconds (default: 60)"
@@ -103,23 +103,23 @@ case $command in
         done
         
         # check if video file is provided
-        [ -z "$video" ] && bin/error "No video file provided" "Please provide a file to chunk" && exit 1
+        [ -z "$video" ] && b/error "No video file provided" "Please provide a file to chunk" && exit 1
 
         # check if chunk size is provided
-        [ -z "$duration" ] && bin/error "No chunk duration provided" "Please provide a chunk duration" && exit 1
+        [ -z "$duration" ] && b/error "No chunk duration provided" "Please provide a chunk duration" && exit 1
 
         # check if video file exists
-        [ ! -f "$video" ] && bin/error "video file not found" "Please provide a valid file" && exit 1
+        [ ! -f "$video" ] && b/error "video file not found" "Please provide a valid file" && exit 1
 
         # check if chunk duration is a number
-        [[ ! "$duration" =~ ^[0-9]+$ ]] && bin/error "Invalid chunk duration" "Please provide a valid number" && exit 1
+        [[ ! "$duration" =~ ^[0-9]+$ ]] && b/error "Invalid chunk duration" "Please provide a valid number" && exit 1
 
         # get video file duration
         total_duration=$(ffprobe -i "$video" -show_entries format=duration -v quiet -of csv="p=0")
 
         # check if video duration is more than 60 minutes
         if (( $(echo "$total_duration > 3600" | bc -l) )); then
-            bin/error "Video duration is too long" "Please provide a video of duration less than or equal to 60 minutes"
+            b/error "Video duration is too long" "Please provide a video of duration less than or equal to 60 minutes"
             exit 1
         fi
 
@@ -129,7 +129,7 @@ case $command in
         # check if video file size is more than 2GB
         file_size=$(stat -f%z "$video")
         if ((file_size > 2000000000)); then
-            bin/error "Video file size is too large" "Please provide a video of size less than or equal to 2GB"
+            b/error "Video file size is too large" "Please provide a video of size less than or equal to 2GB"
             exit 1
         fi
 
@@ -155,8 +155,8 @@ case $command in
 
     # ========================================================================
     merge)
-        [ -z "$1" ] && bin/error "No input files provided" "Please provide files to merge" && exit 1
-        [ -z "$2" ] && bin/error "No output file provided" "Please provide a file to merge" && exit 1
+        [ -z "$1" ] && b/error "No input files provided" "Please provide files to merge" && exit 1
+        [ -z "$2" ] && b/error "No output file provided" "Please provide a file to merge" && exit 1
         ffmpeg -i "concat:$1" -c copy "$2"
         ;;
 
@@ -165,7 +165,7 @@ case $command in
     # ========================================================================
     video.240)
 
-        [ -z "$1" ] && bin/usage -t options -w 4 $0 \
+        [ -z "$1" ] && b/usage -t options -w 4 $0 \
             -v "* Input file" \
             -o "  Output file (default: ./tmp/xxxxxxxxxx)" \
             -s "  Suppress process" \
@@ -193,7 +193,7 @@ case $command in
     # ========================================================================
     video.360)
 
-        [ -z "$1" ] && bin/usage -t options -w 4 $0 \
+        [ -z "$1" ] && b/usage -t options -w 4 $0 \
             -v "* Input file" \
             -o "  Output file (default: ./tmp/xxxxxxxxxx)" \
             -s "  Suppress process" \
@@ -222,7 +222,7 @@ case $command in
     # ========================================================================
     video.720)
 
-        [ -z "$1" ] && bin/usage -t options -w 4 $0 \
+        [ -z "$1" ] && b/usage -t options -w 4 $0 \
             -v "* Input file" \
             -o "  Output file (default: ./tmp/xxxxxxxxxx)" \
             -s "  Suppress process" \
@@ -250,7 +250,7 @@ case $command in
 
     # ========================================================================
     *)
-        bin/error "Invalid command" "Please provide a valid command" && exit 1
+        b/error "Invalid command" "Please provide a valid command" && exit 1
         ;;
 
 
