updates documentation style

diff --git a/b/daily b/b/daily
--- a/b/daily
+++ b/b/daily
@@ -1,10 +1,7 @@
 #!/usr/bin/env bash
-# Print usage information for a script or command
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"
 
-# ================================== DOC ===================================
-
-doc=$(cat <<'EOF'
+doc="$(cat <<'EOF'
 
 # daily
 
@@ -16,7 +13,10 @@ Daily.co API
 > b/daily rooms.create -n "My Room" -p private -l 5		| Create a new room
 
 EOF
-) && export doc && b/inspect "$@"
+)" && inspect "$doc" "$1"
+# =============================================================================
+
+
 
 [ -z "$DAILY_API_KEY" ] && b/error missing_key "Daily.co API key not set (DAILY_API_KEY)" && exit 1
 
@@ -25,7 +25,7 @@ shift
 
 case $command in
 
-    rooms.create ) doc=$(cat <<'EOF'
+    rooms.create ) doc="$(cat <<'EOF'
 
 # daily rooms.create
 
@@ -45,87 +45,88 @@ Create a new room
 > b/daily rooms.create -n "My Room" -p private -l 5		| Create a new room
 
 EOF
-) && export doc && b/inspect "$@"
+	)" && inspect "$doc" "$1"
+	# ======================
 
-        while getopts "hn:p:w:x:l:s:k:e:r:t" opt; do
-            case $opt in
-                h ) b/usage -t options -w 4 $0 \
-                    -n "sets the name of the room" \
-                    -p "sets the privacy of the room" \
-                    -w "sets the not before date" \
-                    -x "sets the expiration date" \
-                    -l "sets the participants limit" \
-                    -s "sets the screensharing" \
-                    -k "sets the knocking" \
-                    -e "sets the eject at expiration" \
-                    -r "allow recording" \
-                    -t "allows transcription" && exit 0 ;;
-                n ) name=${OPTARG:-$(b/random string)} ;;
-                p ) privacy=${OPTARG:-'private'} ;;
-                w ) not_before=$OPTARG ;;
-                x ) expires=$OPTARG ;;
-                l ) participants_limit=${OPTARG:-2} ;;
-                s ) screensharing=${OPTARG:-true} ;;
-                k ) knocking=${OPTARG:-true} ;;
-                e ) eject_at_expiration=${OPTARG:-false} ;;
-                r ) recordable=${OPTARG:-'cloud'} ;;
-                t ) transcribable=${OPTARG:-false} ;;
-                \? ) echo "Invalid option: -$OPTARG" ;;
-            esac
-        done
+	while getopts "hn:p:w:x:l:s:k:e:r:t" opt; do
+		case $opt in
+			h ) b/usage -t options -w 4 $0 \
+				-n "sets the name of the room" \
+				-p "sets the privacy of the room" \
+				-w "sets the not before date" \
+				-x "sets the expiration date" \
+				-l "sets the participants limit" \
+				-s "sets the screensharing" \
+				-k "sets the knocking" \
+				-e "sets the eject at expiration" \
+				-r "allow recording" \
+				-t "allows transcription" && exit 0 ;;
+			n ) name=${OPTARG:-$(b/random string)} ;;
+			p ) privacy=${OPTARG:-'private'} ;;
+			w ) not_before=$OPTARG ;;
+			x ) expires=$OPTARG ;;
+			l ) participants_limit=${OPTARG:-2} ;;
+			s ) screensharing=${OPTARG:-true} ;;
+			k ) knocking=${OPTARG:-true} ;;
+			e ) eject_at_expiration=${OPTARG:-false} ;;
+			r ) recordable=${OPTARG:-'cloud'} ;;
+			t ) transcribable=${OPTARG:-false} ;;
+			\? ) echo "Invalid option: -$OPTARG" ;;
+		esac
+	done
 
-        # Ensure the variables are set to a valid JSON value
-        [ -z "$screensharing" ] && screensharing=true
-        [ -z "$knocking" ] && knocking=true
-        [ -z "$eject_at_expiration" ] && eject_at_expiration=false
-        [ -z "$transcribable" ] && transcribable=false
-        [ -z "$participants_limit" ] && participants_limit=2
+	# Ensure the variables are set to a valid JSON value
+	[ -z "$screensharing" ] && screensharing=true
+	[ -z "$knocking" ] && knocking=true
+	[ -z "$eject_at_expiration" ] && eject_at_expiration=false
+	[ -z "$transcribable" ] && transcribable=false
+	[ -z "$participants_limit" ] && participants_limit=2
 
-        # Start of the JSON payload
-        json_payload=$(jq -n \
-            --arg name "$name" \
-            --arg privacy "$privacy" \
-            --argjson screensharing "$screensharing" \
-            --argjson knocking "$knocking" \
-            --argjson eject_at_expiration "$eject_at_expiration" \
-            --arg transcribable "$transcribable" \
-            --argjson participants_limit "$participants_limit" \
-            --arg not_before "$not_before" \
-            '{
-                "name": $name,
-                "privacy": $privacy,
-                "properties": {
-                    "enable_screenshare": $screensharing,
-                    "enable_knocking": $knocking,
-                    "enable_advanced_chat": true,
-                    "eject_at_room_exp": $eject_at_expiration,
-                    "enable_transcription_storage": true,
-                    "max_participants": $participants_limit,
-                    "nbf": $not_before
-                }
-            }')
+	# Start of the JSON payload
+	json_payload=$(jq -n \
+		--arg name "$name" \
+		--arg privacy "$privacy" \
+		--argjson screensharing "$screensharing" \
+		--argjson knocking "$knocking" \
+		--argjson eject_at_expiration "$eject_at_expiration" \
+		--arg transcribable "$transcribable" \
+		--argjson participants_limit "$participants_limit" \
+		--arg not_before "$not_before" \
+		'{
+			"name": $name,
+			"privacy": $privacy,
+			"properties": {
+				"enable_screenshare": $screensharing,
+				"enable_knocking": $knocking,
+				"enable_advanced_chat": true,
+				"eject_at_room_exp": $eject_at_expiration,
+				"enable_transcription_storage": true,
+				"max_participants": $participants_limit,
+				"nbf": $not_before
+			}
+		}')
 
-        # Conditionally add 'enable_recording' to the JSON payload
-        if [ -n "$recordable" ]; then
-            json_payload=$(echo $json_payload | jq --arg recordable "$recordable" '.properties.enable_recording = $recordable')
-        fi
+	# Conditionally add 'enable_recording' to the JSON payload
+	if [ -n "$recordable" ]; then
+		json_payload=$(echo $json_payload | jq --arg recordable "$recordable" '.properties.enable_recording = $recordable')
+	fi
 
-        # Conditionally add 'exp' to the JSON payload
-        if [ -n "$expires" ]; then
-            json_payload=$(echo $json_payload | jq --arg expires "$expires" '.properties.exp = $expires')
-        fi
+	# Conditionally add 'exp' to the JSON payload
+	if [ -n "$expires" ]; then
+		json_payload=$(echo $json_payload | jq --arg expires "$expires" '.properties.exp = $expires')
+	fi
 
-        response=$(curl https://api.daily.co/v1/rooms -s \
-            -H "Content-Type: application/json" \
-            -H "Authorization: Bearer $DAILY_API_KEY" \
-            -d "$json_payload") || { b/error api_error "Failed to create room"; exit 1; }
+	response=$(curl https://api.daily.co/v1/rooms -s \
+		-H "Content-Type: application/json" \
+		-H "Authorization: Bearer $DAILY_API_KEY" \
+		-d "$json_payload") || { b/error api_error "Failed to create room"; exit 1; }
 
-        echo "$response" | jq
+	echo "$response" | jq
 
-        ;;
+	;;
 
 
-    transcriptions.list ) doc=$(cat <<'EOF'
+	transcriptions.list ) doc="$(cat <<'EOF'
 
 # daily transcriptions.list
 
@@ -136,15 +137,16 @@ List transcriptions
 > daily transcriptions.list		| List transcriptions
 
 EOF
-) && export doc && b/inspect "$@"
+	)" && inspect "$doc" "$1"
+	# ======================
 
-        response=$(curl https://api.daily.co/v1/transcript -s \
-            -H "Content-Type: application/json" \
-            -H "Authorization: Bearer $DAILY_API_KEY") || { b/error api_error "Failed to list transcriptions"; exit 1; }
+	response=$(curl https://api.daily.co/v1/transcript -s \
+		-H "Content-Type: application/json" \
+		-H "Authorization: Bearer $DAILY_API_KEY") || { b/error api_error "Failed to list transcriptions"; exit 1; }
 
-        echo "$response" | jq
+	echo "$response" | jq
 
-        ;;
+	;;
 
 
 esac
diff --git a/b/openai b/b/openai
--- a/b/openai
+++ b/b/openai
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"
-
 doc="$(cat <<'EOF'
 
 # openai
@@ -28,7 +27,9 @@ OpenAI API client
 > openai thread.messages.list -t "thread_id"									| List messages in a thread
 
 EOF
-)" && b/inspect "$@"
+)" && inspect "$doc" "$1"
+# =============================================================================
+
 
 
 # Requirements
@@ -68,7 +69,6 @@ api_url="https://api.openai.com/v1"
 default_model="gpt-3.5-turbo-0125"
 command="$1" && shift
 
-
 # Parse command line options
 case "$command" in
 
@@ -90,7 +90,8 @@ Send a message to an AI model
 > openai chat -m "What is the capital of France?" -a "You are a helpful AI assistant."	| Send a message to an AI model
 
 EOF
-		)" && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
 		format="text"
 		message="$1"
@@ -103,7 +104,7 @@ EOF
 				o ) model="$OPTARG" ;;
 				j ) format="json_object" ;;
 				V ) verbose=true ;;
-				* ) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
+				* ) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
 			esac
 		done
 
@@ -139,7 +140,8 @@ Create a new assistant
 > openai assistants.create -n "My Assistant" -i "This is a helpful assistant"	| Create a new assistant
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
         tools=()
         model=$default_model
@@ -195,7 +197,8 @@ Create a new thread
 > openai threads.create -m "Hello, world!"	| Create a new thread
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
         file_ids=""
 
@@ -245,7 +248,8 @@ Append a message to a thread
 > openai thread.messages.append -t "thread_id" -m "Hello, world!"	| Append a message to a thread
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
 		file_ids="[]"
 
@@ -294,7 +298,8 @@ List messages in a thread
 > openai thread.messages.list -t "thread_id"	| List messages in a thread
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
         limit=5
         
@@ -339,7 +344,8 @@ Run an assistant on a thread
 > openai thread.run -t "thread_id" -a "assistant_id"	| Run an assistant on a thread
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
 		while getopts ":t:a:JV" opt; do
 			case ${opt} in
@@ -384,7 +390,8 @@ Poll the status of a thread run
 > openai thread.run.poll -t "thread_id" -r "run_id"	| Poll the status of a thread run
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
         while getopts ":t:r:JV" opt; do
             case ${opt} in
@@ -425,7 +432,8 @@ Upload a file to the OpenAI API
 > openai files.upload -f "path/to/file"	| Upload a file to the OpenAI API
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
         purpose="assistants"
         while getopts ":f:p:JV" opt; do
@@ -464,7 +472,8 @@ List files uploaded to the OpenAI API
 > openai files.list	| List files uploaded to the OpenAI API
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
 		purpose="assistants"
 		while getopts ":p:JV" opt; do
@@ -504,7 +513,8 @@ Show details of a file uploaded to the OpenAI API
 > openai file.show -f "file_id"	| Show details of a file uploaded to the OpenAI API
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
     
 		while getopts ":f:JV" opt; do
 			case ${opt} in
@@ -542,7 +552,8 @@ Delete a file from the OpenAI API
 > openai file.delete -f "file_id"	| Delete a file from the OpenAI API
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
     
 		while getopts ":f:JV" opt; do
 			case ${opt} in
@@ -586,7 +597,8 @@ Generate images from a prompt
 > openai images.create -p "A painting of a sunset over the ocean"	| Generate images from a prompt
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
     
 		model="dall-e-3"
 		n=1
@@ -655,7 +667,8 @@ Generate audio from a text prompt
 > openai audio.create -i "Hello, world!"	| Generate audio from a text prompt
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
     
 		model="tts-1"
 		voice="alloy"
@@ -725,7 +738,8 @@ Transcribe an audio file
 > openai audio.transcribe -f "path/to/audio"	| Transcribe an audio file
 
 EOF
-		)" && export doc && b/inspect "$@"
+		)" && inspect "$doc" "$1"
+		# ======================
 
         language="en"
         output_file="$BARE_DIR/tmp/transcription-$(date +%Y%m%d-%H%M%S).txt"
