refactor

diff --git a/b/notes b/b/notes
--- a/b/notes
+++ b/b/notes
@@ -51,7 +51,7 @@ case $command in
 		) && [[ "$1" == '--inspect' ]] && return 0
 
 		declare -a args=()
-		args+=("--no-color" "--no-indicator")
+		args+=("--no-color" "--no-indicator" "--filenames")
 		while getopts "l:t:rN:" opt; do
 			case $opt in
 				l ) args+=("--limit" "$OPTARG"); shift 2 ;;
@@ -88,25 +88,26 @@ case $command in
 			nb show "$id" --print
 		fi
 
-        ;;
+		;;
 
     create )
 
 		doc_name+=" create"
 		doc_description="Create a new note"
 		declare -a doc_options=(
-			"-T"		"Title of the note"
-			"-C"		"Content of the note"
-			"-t"		"Comma-separated tags for the note (my-tag,tag2,another-tag)"
-			"-E"		"Encrypt the note"
-			"-P"		"Password for the note"
-			"-N"		"Notebook to save the note in (defaults to 'home')"
-			"-F"		"Folder to save the note in"
-			"-f"		"Filename for the note"
+			"-T"	"Title of the note"
+			"-C"	"Content of the note"
+			"-t"	"Comma-separated tags for the note (my-tag,tag2,another-tag)"
+			"-E"	"Encrypt the note"
+			"-P"	"Password for the note"
+			"-N"	"Notebook to save the note in (defaults to 'home')"
+			"-F"	"Folder to save the note in"
+			"-f"	"Filename for the note"
 		) && [[ "$1" == '--inspect' ]] && return 0
 
         notebook="home"
-        declare -a content=("- - - - -")
+		title="$1"
+        declare -a content=()
         while getopts "T:C:t:EP:N:F:f:" opt; do
             case $opt in
                 T ) title=$OPTARG ;;
@@ -128,14 +129,10 @@ case $command in
             esac
         done
 
-        # make sure at least title or content is set
-		[ -z "$title" ] && [ -z "$content" ] && echo "Error: Must provide a title (-T) or content (-C)" && exit 1
-
         # if -E is set, -P must also be set
         [ -n "$encrypt" ] && [ -z "$password" ] && echo "Error: Encryption flag (-E) requires a password (-P)" && exit 1
 
         declare -a args=("$notebook:add" "--no-color")
-
         [ -n "$title" ] && args+=("--title" "$title")
 		for item in "${content[@]}"; do args+=("--content" "$item"); done
         [ -n "$tags" ] && args+=("--tags" "$tags")
@@ -143,24 +140,48 @@ case $command in
         [ -n "$folder" ] && args+=("--folder" "$folder")
         [ -n "$filename" ] && args+=("--filename" "$filename")
 
-		output=$(nb "${args[@]}")
-		id=$(echo "$output" | awk -F'[][]' '{print $2}')
-		echo "$id"
+		[[ -z "$content" ]] && output=$(echo "" | nb "${args[@]}")
+		[[ -n "$content" ]] && output=$(nb "${args[@]}")
+
+		id=$(echo "$output" | awk -F'[][]' '{print $2}') && echo "$id"
         ;;
+
+	open )
+
+		doc_name+=" open"
+		doc_description="Open a note in the default editor"
+		declare -a doc_options=(
+			"<:id>"		"Open a note by given ID"
+			"-N"		"Notebook to open the note from"
+		) && [[ "$1" == '--inspect' ]] && return 0
+
+		id="$1" && shift
+		notebook="home"
+		while getopts "N:" opt; do
+			case $opt in
+				N ) notebook=$OPTARG ;;
+				* ) echo "Invalid option: -$OPTARG" 1>&2; exit 1 ;;
+			esac
+		done
+
+		nb use "$notebook" > /dev/null
+		nb edit "$id" --edit
+
+		;;
 
     edit )
 
 		doc_name+=" edit"
 		doc_description="Edit a note"
 		declare -a doc_options=(
-			"-n"		"ID of the note"
-			"-T"		"Title of the note"
-			"-C"		"Content of the note"
-			"-E"		"Encrypt the note"
-			"-P"		"Password for the note"
-			"-N"		"Notebook to save the note in (defaults to 'home')"
-			"-F"		"Folder to save the note in"
-			"-f"		"Filename for the note"
+			"-n"	"ID of the note"
+			"-T"	"Title of the note"
+			"-C"	"Content of the note"
+			"-E"	"Encrypt the note"
+			"-P"	"Password for the note"
+			"-N"	"Notebook to save the note in (defaults to 'home')"
+			"-F"	"Folder to save the note in"
+			"-f"	"Filename for the note"
 		) && [[ "$1" == '--inspect' ]] && return 0
 
 		id="$1" && shift
@@ -179,14 +200,7 @@ case $command in
                 f ) filename=$OPTARG ;;
 				s ) silent=true ;;
 				a ) append=true ;;
-                \? )
-                    echo "Invalid option: -$OPTARG" 1>&2
-                    exit 1
-                    ;;
-                : )
-                    echo "Option -$OPTARG requires an argument." 1>&2
-                    exit 1
-                    ;;
+				* ) echo "Invalid option: -$OPTARG" 1>&2; exit 1 ;;
             esac
         done
 
diff --git a/b/openai b/b/openai
--- a/b/openai
+++ b/b/openai
@@ -73,8 +73,7 @@ case $command in
 
 
     # ========================================================
-    chat )
-
+	chat )
 		doc_name+=" chat"
 		doc_description="Send a message to an AI model"
 
@@ -82,45 +81,37 @@ case $command in
 			"-m" "* The message to send"
 			"-a" "  The system prompt (assistant prompt)"
 			"-o" "  The model to use"
-			"-j" "  Requests OpenAI's response as JSON"
-			"-J" "  Return as verbose JSON object"
+			"-j" "  Requests OpenAI's response be JSON"
 			"-V" "  Return the vendor response, verbosely"
 		) && [[ $1 == "--inspect" ]] && return 0
 
-        format="text"
-        raw_json=false
+		format="text"
+		message="$1"
+		assistant_prompt="${2:-You are a helpful AI assistant.}"
+		model="$default_model"
+		while getopts ":m:a:o:jV" opt; do
+			case ${opt} in
+				m ) message="$OPTARG" ;;
+				a ) assistant_prompt="$OPTARG" ;;
+				o ) model="$OPTARG" ;;
+				j ) format="json_object" ;;
+				V ) verbose=true ;;
+				* ) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
+			esac
+		done
 
-        while getopts ":m:a:o:jJv" opt; do
-            case ${opt} in
-                m ) message="$OPTARG" ;;
-                o ) model="$OPTARG" ;;
-                a ) assistant_prompt="${OPTARG:-You are a helpful AI assistant.}" ;;
-                j ) format="json_object" ;;
-                J ) respond="as_json" ;;
-                v ) verbose=true ;;
-                \? ) b/error invalid_option "-$OPTARG" ;;
-                : ) IFS= read -rd '' -n 1 message <&0 ;;
-            esac
-        done
+		response=$(curlRequest -u "$api_url/chat/completions" -d "$(jq -n --arg assistant_prompt "${assistant_prompt}" --arg model "${model}" --arg content "$message" --arg format "${format}" '{
+			model: $model,
+			response_format: { "type": $format },
+			messages: [
+				{ role: "system", content: $assistant_prompt },
+				{ role: "user", content: $content }
+			]
+		}')" -j)
+		content=$(echo "$response" | jq -r '.choices[0].message.content')
 
-        message_payload=$(jq -n --arg assistant_prompt "${assistant_prompt}" --arg model "${model:-$default_model}" --arg content "$message" --arg format "${format:-text}" '{
-            model: $model,
-            response_format: { "type": $format },
-            messages: [ { role: "system", content: $assistant_prompt }, { role: "user", content: $content } ]
-        }')
-
-        response=$(curlRequest -u "$api_url/chat/completions" -d "$message_payload" -j)
-
-        if [[ "$verbose" == true ]]; then
-            echo "$response" | jq -r
-        elif [[ "$format" == "json_object" ]]; then
-            echo "$response" | jq -r '.choices[0].message.content' | jq
-        elif [[ "$respond" == "as_json" ]]; then
-            echo "$response" | jq -r '{response: .choices[0].message.content}'
-        else
-            echo "$response" | jq -r '.choices[0].message.content'
-        fi
-        ;;
+		[[ $verbose ]] && echo "$response" | jq || echo "$content"
+		;;
 
 
 
