updates notes path

diff --git a/b/notes b/b/notes
--- a/b/notes
+++ b/b/notes
@@ -9,7 +9,7 @@ command="$1"
 shift
 
 # make sure we've initialized the notes
-[[ ! -d $BARE_NOTES_PATH ]] && nb init > /dev/null 2>&1
+[[ ! -d $BARE_NOTES_DIR ]] && nb init > /dev/null 2>&1
 
 case $command in
 
@@ -82,7 +82,7 @@ case $command in
         # if -E is set, -P must also be set
         [ -n "$encrypt" ] && [ -z "$password" ] && echo "Error: Encryption flag (-E) requires a password (-P)" && exit 1
 
-        command=("nb" "$notebook:add")
+        command=("nb" "$notebook:_add" --print --no-color)
 
         [ -n "$title" ] && command+=("--title" "$title")
         [ -n "$content" ] && command+=("--content" "$content")
@@ -91,16 +91,81 @@ case $command in
         [ -n "$folder" ] && command+=("--folder" "$folder")
         [ -n "$filename" ] && command+=("--filename" "$filename")
 
-        "${command[@]}"
+        format_nb_response() {
+            input="$1"
+            id=$(echo "$input" | awk -F'[][]' '{print $2}')
+            filename=$(echo "$input" | awk '{print $3}')
+            title=$(echo "$input" | awk -F'\"' '{print $2}')
+            # echo as json
+            echo "{\"id\":\"$id\",\"filename\":\"$filename\",\"title\":\"$title\"}"
+        }
+
+        output=$("${command[@]}")
+        format_nb_response "$output"
         ;;
+
     edit)
-        note_path="$BARE_NOTES_PATH/$(date +%Y-%m-%d).md"
-        if [ -f $note_path ]; then
-            $EDITOR $note_path
-        else
-            echo "No note found for today. Creating a new note."
-            b/notes add
-        fi
+
+        [[ -z $1 ]] && b/usage -t "options" -w 2 "$0 edit" \
+            -n "* ID of the note to edit" \
+            -T "  Title of the note" \
+            -C "  Content of the note" \
+            -t "  Comma-separated tags for the note (my-tag,tag2,another-tag)" \
+            -E "  Encrypt the note" \
+            -P "= Password for the note" \
+            -N "  Notebook to save the note in (defaults to 'home')" \
+            -F "  Folder to save the note in" \
+            -f "  Filename for the note" && exit 0;
+
+        notebook="home"
+        content=""
+        while getopts "n:T:C:t:EP:N:F:f:" opt; do
+            case $opt in
+                n ) id=$OPTARG ;;
+                T ) title=$OPTARG ;;
+                C ) content=$OPTARG ;;
+                t ) tags=$OPTARG ;;
+                E ) encrypt=$OPTARG ;;
+                P ) password=$OPTARG ;;
+                N ) notebook=$OPTARG ;;
+                F ) folder=$OPTARG ;;
+                f ) filename=$OPTARG ;;
+                \? )
+                    echo "Invalid option: -$OPTARG" 1>&2
+                    exit 1
+                    ;;
+                : )
+                    echo "Option -$OPTARG requires an argument." 1>&2
+                    exit 1
+                    ;;
+            esac
+        done
+
+        # if -E is set, -P must also be set
+        [ -n "$encrypt" ] && [ -z "$password" ] && echo "Error: Encryption flag (-E) requires a password (-P)" && exit 1
+
+        command=("nb" "_edit" --print --no-color)
+
+        [ -n "$id" ] && command+=("--id" "$id")
+        [ -n "$title" ] && command+=("--title" "$title")
+        [ -n "$content" ] && command+=("--content" "$content")
+        [ -n "$tags" ] && command+=("--tags" "$tags")
+        [ -n "$password" ] && command+=("-e" "--password" "$password")
+        [ -n "$folder" ] && command+=("--folder" "$folder")
+        [ -n "$filename" ] && command+=("--filename" "$filename")
+
+        format_nb_response() {
+            input="$1"
+            id=$(echo "$input" | awk -F'[][]' '{print $2}')
+            filename=$(echo "$input" | awk '{print $3}')
+            title=$(echo "$input" | awk -F'\"' '{print $2}')
+            # echo as json
+            echo "{\"id\":\"$id\",\"filename\":\"$filename\",\"title\":\"$title\"}"
+        }
+
+        output=$("${command[@]}")
+        format_nb_response "$output"
+
         ;;
 
     delete )
