makes script editor declarable

diff --git a/b/script b/b/script
--- a/b/script
+++ b/b/script
@@ -30,7 +30,19 @@ case $command in
 
 	list ) b/notes list -N "scripts" ;;
 	show ) b/notes show "scripts:$1" ;;
-	open ) "${BARE_EDITOR:-vim}" "$BARE_HOME/.nb/scripts/$1" ;;
+	open )
+		file="$BARE_HOME/.nb/scripts/$1" && shift
+		editor="${2:-${BARE_EDITOR:-vim}}"
+		while getopts "e:" opt; do
+			case $opt in
+				e ) editor="$OPTARG" ;;
+				* ) echo "Invalid option: -$OPTARG" >&2 ;;
+			esac
+		done
+		shift $((OPTIND-1))
+		# open
+		"$editor" "$file"
+		;;
 	run ) b/interpret "$1" ;;
 	create ) b/notes create -N scripts -T "$1" ;;
 	* ) echo "Invalid command: $command" && exit 1 ;;
