revising sourcing

diff --git a/b/www-setup b/b/www-setup
--- a/b/www-setup
+++ b/b/www-setup
@@ -1,5 +1,5 @@
 #!/bin/bash
-cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../ && source lib/init
+cd "$(dirname "${BASH_SOURCE[0]}")/../" && { [ -f lib/init ] && source lib/init || echo "Cannot find lib/init" && exit 1; }
 
 # check that /var/www/ exists
 if [ ! -d "/var/www" ]; then
